### ISSUE TITLE
Attach VGA interface 

### ISSUE THREAD

**Issue by methadata** [BBVA/kvm#10]
To boot most images (most Linux distros, Windows...) it is needed to attach a VGA on boot. 

Consider to render VGA output to serial port, or simply output serial port to stdout, if the guest vm has been configured to do so.

**Comment by pwFoo** [comment]
Hi @methadata,

I played around and removed some options (serial, nographic, ...) and get a boot process which ends with "1024 x 768 Graphic mode"

So VGA / serial settings could be the problem.

**Comment by ahoeg** [comment]
It seems to boot, but still can't access the VM by exposed ports or container ip (#5).

VGA problem seems to be fixed because container RAM usage increases from ~0 to 725MB. So VM should boot and running now...

Thanks! Great job!

**Comment by methadata** [comment]
Thanks for report @ahoeg 

We have noticed that the upgrade to Alpine crashed the network connectivity. We have reverted the changes, and until we make further investigation, we will keep Centos as base image.

Once we test and solve the connectivity issue with Alpine, we will merge it to master. Until the, we will keep the "alpine" branch.
