### ISSUE TITLE
"The container gets non-conflicting IPs"

### ISSUE THREAD

**Issue by pwFoo** [BBVA/kvm#11]
> The VM gets the original container IPs. The container gets non-conflicting IPs

You increase the subnet mask to have some additional non-conflicting IPs?
Could be conflicting with routed subnets (docker host or external)?

**Comment by methadata** [comment]
Nor really, because the new IP is not routable outside the container. 

Indeed, the "non confilcting IP" is used only for the sake of dnsmasq to serve IP to the VM. Not even the VM can ping its container host in most configurations.
