### ISSUE TITLE
wrong IP?

### ISSUE THREAD

**Issue by segator** [BBVA/kvm#27]
this docker image is setting wrong IP to the docker macvlan

172.16.0.3/15 should be 172.17.0.3/16

1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: macvtapa0761e@eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN qlen 500
    link/ether 02:42:ac:11:00:03 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::42:acff:fe11:3/64 scope link
       valid_lft forever preferred_lft forever
3: macvlana0761e@eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN qlen 1
    link/ether ba:49:20:45:26:86 brd ff:ff:ff:ff:ff:ff
    inet 172.16.0.3/15 scope global macvlana0761e
       valid_lft forever preferred_lft forever
    inet6 fe80::b849:20ff:fe45:2686/64 scope link
       valid_lft forever preferred_lft forever
3824: eth0@if3825: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP
    link/ether fe:05:93:f4:a6:e4 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::fc05:93ff:fef4:a6e4/64 scope link
       valid_lft forever preferred_lft forever

**Comment by methadata** [comment]
Hi, and thanks for taking the time for reporting this.

The container generates a new IP and MASK in a superset (immediate wider range) of the docker0 interface, and "transfers" the original IP to the VM via DHCP.

Thus, it seems to me that IP address is OK in the container, and the one you expect (172.17.0.3) should be assigned to the VM once it starts.

After this process the container itself becomes unreachable, but the VM is.

I will close this issue now. Feel free to re-open it if you think the reply is incorrect, or have an unexpected behaviour.

**Comment by segator** [comment]
I understand but if I try to ping from host to the IP 172.17.0.3(Is the ip I see if I do docker inspect containerID)  I'm not getting response, if I connect via serial to the KVM machine, the machine isn't getting IP from the DHCP, If I try to set the IP 172.17.0.3/24   172.17.0.1(gw) manually to the KVM guest, also don't have response. so something is not working. Could be something related with the machine? is a fresh ubuntu 16.04 OVH machine. Docker is working perfectly, and I have the macvhost enabled in the kernel as you explain in the readme.
Could I share with you something that can help you to find out the problem? Thank you!

**Comment by methadata** [comment]
That's quite odd :-S 
Are you running the container in your host or in a OVH VM?

Anyway, try to run the container with `-e DEBUG='y' ` and paste here the relevant output (if any).

**Comment by segator** [comment]
Hi,
Is a Dedicated OVH host.

docker version
```
docker info
Containers: 22
 Running: 17
 Paused: 0
 Stopped: 5
Images: 95
Server Version: 17.03.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 239
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-66-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.07 GiB
Name: ns320566.ip-37-187-153.eu
ID: ***
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```



execution log
```
INFO: KVM acceleration enabled
DEBUG: Container original MAC address: 02:42:ac:11:00:03
++ local iface=eth0
++ local mode=macvlan
+++ generateNetdevNames macvlan
+++ devicetype=macvlan
+++ netdevinterfaces=($(ip link show | awk "/$devicetype/ { print \$2 }" | cut -d '@' -f 1 | tr -d :))
++++ awk '/macvlan/ { print $2 }'
++++ cut -d @ -f 1
++++ tr -d :
++++ ip link show
+++ local netdevinterfaces
++++ cat /dev/urandom
++++ fold -w 6
++++ tr -dc a-f0-9
++++ head -n 1
+++ local randomID=6793c7
+++ containsElement macvlan6793c7
+++ local e
+++ return 1
+++ echo 6793c7
++ local deviceID=6793c7
++ local bridgeName=macvlan6793c7
++ [[ macvlan == \b\r\i\d\g\e ]]
++ vtapdev=macvtap6793c7
+++ ip link add link eth0 name macvtap6793c7 type macvtap mode bridge
++ ip link set macvtap6793c7 address 02:42:ac:11:00:03
++ ip link set macvtap6793c7 up
++ ip link add link eth0 name macvlan6793c7 type macvlan mode bridge
++ ip link set macvlan6793c7 up
++ IFS=:
++ read major minor
+++ cat /sys/devices/virtual/net/macvtap6793c7/tap2/dev
++ mknod /dev/macvtap6793c7 c 241 1
++ set +x
INFO: DHCP configured to serve IP 172.17.0.3/16 via macvlan6793c7 (attached to container's eth0)
DEBUG: bridgeName: macvlan6793c7
INFO: Lauching dnsmasq
DEBUG: dnsmasq options:  --dhcp-range=172.17.0.3,172.17.0.3 --dhcp-host=02:42:ac:11:00:03,,172.17.0.3,a5489bc581c4,infinite --dhcp-option=option:netmask,255.255.0.0                             --dhcp-option=option:dns-server,213.186.33.99          --dhcp-option=option:router,172.17.0.1            --dhcp-option=option:domain-search,ovh.net     --dhcp-option=option:domain-name,ovh.net
INFO: Launching qemu-kvm
DEBUG: Launching /usr/libexec/qemu-kvm -drive file=/image/boot.img,format=raw,if=none,id=drive-sata0-0-1 -device ide-hd,drive=drive-sata0-0-1,id=sata0-0-1,bootindex=1 -drive file=/image/image,format=qcow2,if=none,id=drive-sata0-0-2,cache=writeback -device ide-hd,drive=drive-sata0-0-2,id=sata0-0-2   -nodefaults   -device virtio-balloon-pci,id=balloon0   -realtime mlock=off   -msg timestamp=on   -chardev pty,id=charserial0   -device isa-serial,chardev=charserial0,id=serial0   -serial stdio    -enable-kvm -machine accel=kvm,usb=off  -vga qxl -display none -m 1024 -smp 4,sockets=4,cores=1,threads=1    -device e1000,netdev=net0,mac=02:42:ac:11:00:03  -netdev tap,id=net0,vhost=on,fd=3 3<>/dev/macvtap6793c7
char device redirected to /dev/pts/0 (label charserial0)

                    GNU GRUB  version 2.02~beta2-9ubuntu1.12

 +----------------------------------------------------------------------------+
 |*DS3615xs 6.02 Baremetal with Jun's Mod v1.0                                |
 | DS3615xs 6.02 Baremetal with Jun's Mod v1.0 Reinstall                      |
 | DS3615xs 6.02 Baremetal with Jun's Mod v1.0 Force Install                  |
 | DS3615xs 6.02 Baremetal AMD with Jun's Mod v1.0                            |
 | DS3615xs 6.02 VMWare/ESXI with Jun's Mod v1.0                              |
 |                                                                            |
 |                                                                            |
 |                                                                            |
 |                                                                            |
 |                                                                            |
 |                                                                            |
 |                                                                            |
 +----------------------------------------------------------------------------+

      Use the ^ and v keys to select which entry is highlighted.
      Press enter to boot the selected OS, `e' to edit the commands
      before booting or `c' for a command-line.
   The highlighted entry will be executed automatically in 0s.
START /linuxrc.syno
Insert basic USB modules...
:: Loading module usb-common ... [  OK  ]
:: Loading module usbcore ... [  OK  ]
:: Loading module ehci-hcd ... [  OK  ]
:: Loading module ehci-pci ... [  OK  ]
:: Loading module uhci-hcd ... [  OK  ]
:: Loading module xhci-hcd ... [  OK  ]
:: Loading module etxhci-hcd ... [  OK  ]
:: Loading module usb-storage ... [  OK  ]
rc.extras in linuxrc.syno
:: Loading module BusLogic ... [  OK  ]
:: Loading module vmw_pvscsi ... [  OK  ]
:: Loading module megaraid_mm ... [  OK  ]
:: Loading module megaraid_mbox ... [  OK  ]
:: Loading module megaraid ... [  OK  ]
:: Loading module scsi_transport_spi ... [  OK  ]
:: Loading module mptbase ... [  OK  ]
:: Loading module mptscsih ... [  OK  ]
:: Loading module mptspi ... [  OK  ]
:: Loading module mptsas ... [  OK  ]
:: Loading module mptctl ... [  OK  ]
:: Loading module ata_piix[    2.829164] ata2: Read current link speed fail, retry 1
[    2.835101] ata2: Read current link speed fail, retry 2
[    2.841101] ata2: Read current link speed fail, retry 3
[    2.848089] ata1: Read current link speed fail, retry 1
[    2.855215] ata1: Read current link speed fail, retry 2
[    2.867117] ata1: Read current link speed fail, retry 3
 ... [  OK  ]
:: Loading module megaraid_sas ... [  OK  ]
:: Loading module mpt2sas ... [  OK  ]
:: Loading module mpt3sas ... [  OK  ]
Insert net driver(Mindspeed only)...
Starting /usr/syno/bin/synocfgen...
/usr/syno/bin/synocfgen returns 0
Partition Version=8
 /sbin/e2fsck exists, checking /dev/md0...

       28660 inodes used (18.41%, out of 155648)
          17 non-contiguous files (0.1%)
           8 non-contiguous directories (0.0%)
             # of inodes with ind/dind/tind blocks: 0/0/0
             Extent depth histogram: 26012/4
      229652 blocks used (36.89%, out of 622544)
           0 bad blocks
           1 large file

       22812 regular files
        2913 directories
           2 character device files
           0 block device files
           0 fifos
        1315 links
        2924 symbolic links (2634 fast symbolic links)
           0 sockets
------------
       29966 files
/sbin/e2fsck returns 0
Mounting /dev/md0 /tmpRoot
------------upgrade
Begin upgrade procedure
No upgrade file exists
End upgrade procedure
============upgrade
Wait 2 seconds for synology manufactory device
Thr Mar 30 09:15:09 UTC 2017
/dev/md0 /tmpRoot ext4 rw,relatime,journal_checksum,data=ordered 0 0
none /sys/kernel/debug debugfs rw,relatime 0 0
sys /sys sysfs rw,relatime 0 0
none /dev devtmpfs rw,relatime,size=504916k,nr_inodes=126229,mode=755 0 0
proc /proc proc rw,relatime 0 0
linuxrc.syno executed successfully.
Post init
rc.extras in init.post

==================== start udevd ====================
===== trigger device plug event =====

```

I modified a little bit qemu parameters because I need e1000 eth network because this OS don't work with viritio. If I access inside the VM I can see the eth but it seems doesn't detect DHCP

**Comment by methadata** [comment]
It seems to me that the guest VM doesn't try to get its IP via DHCP. If so, normally it'd have some lines in the log with something like "getting IP address", "dhcp timeout" or so.
Have you tried to access the VM via console and configure the IP manually? Have you tried to launch `dhclient eth0` in the guest VM? You can do so by connecting to the VM console. See qemu-kvm manpage for options on connecting to the console.

As you can see, container is getting IP 172.16.0.3/15, and the guest VM would get container's original IP address 172.17.0.3/16, as logs suggest it's configured in DHCP server.

**Comment by segator** [comment]
I fully sure VM is using DHCP because if I run same qcow2 disk in libvirtd works perfect.
And I also tried to set manually the IP and there aren't response.

Also tried your docker directly without modifications with simple ubuntu and doesn't work also. probably it is something related with my environment but I not sure how to find out the problem.

**Comment by methadata** [comment]
In this case, probably there's something wrong/too enforced with virtual networking permissions (or the SDN used in OVH machines)  in the VM.

Just to discard macvlan incompatibilities, try to launch the container using `USE_NET_BRIDGES='Y'`and see if it works. Try also to configure the IP manually in the container in this mode, if dhcp doesn't work.

**Comment by segator** [comment]
HI, With USE_NET_BRIDGES DHCP doesn't work but if I set the IP manually I can have access from the host and from internet (if I map ports with -p)

**Comment by segator** [comment]
Hi, I finally fixed the problem, the problem is the guest I am using use fixed MAC so doesn't match with used MAC by the created bridge.
I modified startVM to use a hardcoded MAC and all start to working. Thank your for your work!
